"""Market analysis helpers."""

from atlas_trader.analysis.candles import (
    CandleAnalysisSettings,
    CandleClosePosition,
    CandleContext,
    CandleDirection,
    CandleMetrics,
    CandleRangeContext,
    CandleStrength,
    CandleType,
    analyze_candle,
    analyze_candle_contexts,
    analyze_candles,
    closes_above_previous_high,
    closes_below_previous_low,
    has_higher_high_than_previous,
    has_higher_low_than_previous,
    has_lower_high_than_previous,
    has_lower_low_than_previous,
    is_inside_bar,
    is_outside_bar,
)
from atlas_trader.analysis.ranges import (
    BreakoutDirection,
    MarketStructureSettings,
    SidewaysMarketAnalysis,
    SidewaysMarketType,
    analyze_sideways_market,
)
from atlas_trader.analysis.trends import (
    SwingPoint,
    SwingPointType,
    TrendAnalysis,
    TrendAnalysisSettings,
    TrendDirection,
    analyze_trend,
    find_swing_highs,
    find_swing_lows,
    find_swing_points,
)

__all__ = [
    "BreakoutDirection",
    "CandleAnalysisSettings",
    "CandleClosePosition",
    "CandleContext",
    "CandleDirection",
    "CandleMetrics",
    "CandleRangeContext",
    "CandleStrength",
    "CandleType",
    "MarketStructureSettings",
    "SidewaysMarketAnalysis",
    "SidewaysMarketType",
    "SwingPoint",
    "SwingPointType",
    "TrendAnalysis",
    "TrendAnalysisSettings",
    "TrendDirection",
    "analyze_candle",
    "analyze_candle_contexts",
    "analyze_candles",
    "analyze_sideways_market",
    "analyze_trend",
    "closes_above_previous_high",
    "closes_below_previous_low",
    "find_swing_highs",
    "find_swing_lows",
    "find_swing_points",
    "has_higher_high_than_previous",
    "has_higher_low_than_previous",
    "has_lower_high_than_previous",
    "has_lower_low_than_previous",
    "is_inside_bar",
    "is_outside_bar",
]
