"""Market analysis helpers."""

from atlas_trader.analysis.candles import (
    CandleClosePosition,
    CandleContext,
    CandleDirection,
    CandleMetrics,
    CandleRangeContext,
    CandleStrength,
    CandleType,
    analyze_candle,
    analyze_candle_contexts,
    analyze_candles,
    closes_above_previous_high,
    closes_below_previous_low,
    has_higher_high_than_previous,
    has_higher_low_than_previous,
    has_lower_high_than_previous,
    has_lower_low_than_previous,
    is_inside_bar,
    is_outside_bar,
)

__all__ = [
    "CandleClosePosition",
    "CandleContext",
    "CandleDirection",
    "CandleMetrics",
    "CandleRangeContext",
    "CandleStrength",
    "CandleType",
    "analyze_candle",
    "analyze_candle_contexts",
    "analyze_candles",
    "closes_above_previous_high",
    "closes_below_previous_low",
    "has_higher_high_than_previous",
    "has_higher_low_than_previous",
    "has_lower_high_than_previous",
    "has_lower_low_than_previous",
    "is_inside_bar",
    "is_outside_bar",
]
