"""Background watchlist runner for market-reading validation."""

import csv
import json
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from time import sleep
from typing import Any

from atlas_trader.analysis.multi_timeframe import (
    MultiTimeframeAnalysis,
    MultiTimeframeSettings,
    analyze_multi_timeframe,
)
from atlas_trader.data.live import (
    DEFAULT_SWING_POSITION_TIMEFRAMES,
    LiveTimeframeSpec,
    fetch_multi_timeframe_candles,
)
from atlas_trader.reporting.pdf_report import write_text_pdf

DEFAULT_WATCHLIST_MULTI_TIMEFRAME_SETTINGS = MultiTimeframeSettings(
    recent_timeframe="4h",
    primary_timeframe="1d",
    long_term_timeframe="1wk",
)


@dataclass(frozen=True)
class WatchlistServerSettings:
    """Settings for periodic watchlist market reads."""

    symbols: tuple[str, ...]
    output_dir: Path = Path("runtime/watchlist")
    poll_seconds: int = 60 * 60
    max_cycles: int | None = None
    timeframe_specs: tuple[LiveTimeframeSpec, ...] = DEFAULT_SWING_POSITION_TIMEFRAMES
    multi_timeframe_settings: MultiTimeframeSettings = DEFAULT_WATCHLIST_MULTI_TIMEFRAME_SETTINGS
    write_pdf: bool = True
    write_json: bool = True
    write_csv: bool = True

    def __post_init__(self) -> None:
        """Validate server settings."""
        if not self.symbols:
            raise ValueError("symbols must contain at least one symbol.")
        if any(not symbol.strip() for symbol in self.symbols):
            raise ValueError("symbols must not contain blank entries.")
        if self.poll_seconds <= 0:
            raise ValueError("poll_seconds must be greater than zero.")
        if self.max_cycles is not None and self.max_cycles <= 0:
            raise ValueError("max_cycles must be greater than zero.")
        if not self.timeframe_specs:
            raise ValueError("timeframe_specs must contain at least one timeframe.")


@dataclass(frozen=True)
class WatchlistRunResult:
    """Files and reports generated by one watchlist cycle."""

    generated_at: datetime
    reports: list[dict[str, Any]]
    errors: list[dict[str, str]]
    json_path: Path | None
    csv_path: Path | None
    pdf_path: Path | None


def run_watchlist_server(
    settings: WatchlistServerSettings,
    *,
    ticker_factory: Callable[[str], Any] | None = None,
) -> list[WatchlistRunResult]:
    """Run periodic watchlist cycles until max_cycles is reached."""
    results: list[WatchlistRunResult] = []
    cycle = 0
    while settings.max_cycles is None or cycle < settings.max_cycles:
        results.append(run_watchlist_cycle(settings, ticker_factory=ticker_factory))
        cycle += 1
        if settings.max_cycles is not None and cycle >= settings.max_cycles:
            break
        sleep(settings.poll_seconds)
    return results


def run_watchlist_cycle(
    settings: WatchlistServerSettings,
    *,
    ticker_factory: Callable[[str], Any] | None = None,
    generated_at: datetime | None = None,
) -> WatchlistRunResult:
    """Run one watchlist fetch/analyze/persist cycle."""
    generated_at = generated_at or datetime.now(UTC).replace(tzinfo=None)
    reports: list[dict[str, Any]] = []
    errors: list[dict[str, str]] = []

    for symbol in settings.symbols:
        normalized_symbol = symbol.strip().upper()
        try:
            timeframe_candles = fetch_multi_timeframe_candles(
                normalized_symbol,
                specs=settings.timeframe_specs,
                ticker_factory=ticker_factory,
            )
            analysis = analyze_multi_timeframe(
                timeframe_candles,
                settings=settings.multi_timeframe_settings,
            )
            reports.append(_analysis_report(normalized_symbol, generated_at, analysis))
        except Exception as exc:
            errors.append({"symbol": normalized_symbol, "error": str(exc)})

    settings.output_dir.mkdir(parents=True, exist_ok=True)
    json_path = (
        _write_json_report(settings, generated_at, reports, errors) if settings.write_json else None
    )
    csv_path = (
        _append_csv_summary(settings, generated_at, reports, errors) if settings.write_csv else None
    )
    pdf_path = (
        _write_pdf_report(settings, generated_at, reports, errors) if settings.write_pdf else None
    )

    return WatchlistRunResult(
        generated_at=generated_at,
        reports=reports,
        errors=errors,
        json_path=json_path,
        csv_path=csv_path,
        pdf_path=pdf_path,
    )


def _analysis_report(
    symbol: str,
    generated_at: datetime,
    analysis: MultiTimeframeAnalysis,
) -> dict[str, Any]:
    return {
        "symbol": symbol,
        "generated_at": generated_at.isoformat(),
        "directional_bias": analysis.directional_bias.value,
        "alignment": analysis.alignment.value,
        "confidence": analysis.confidence,
        "conflicts": analysis.conflicts,
        "timeframes": {
            timeframe: _timeframe_report(timeframe_analysis)
            for timeframe, timeframe_analysis in analysis.timeframes.items()
        },
        "actionability": "watch_only",
    }


def _timeframe_report(timeframe_analysis: Any) -> dict[str, Any]:
    latest = timeframe_analysis.latest_candle
    nearest_support = timeframe_analysis.support_resistance.nearest_support
    nearest_resistance = timeframe_analysis.support_resistance.nearest_resistance
    volume = timeframe_analysis.volume
    return {
        "role": timeframe_analysis.role.value,
        "candle_count": len(timeframe_analysis.candles),
        "latest_timestamp": latest.timestamp.isoformat() if latest else None,
        "latest_close": latest.close if latest else None,
        "bias": timeframe_analysis.bias.value,
        "confidence": timeframe_analysis.confidence,
        "trend_direction": timeframe_analysis.trend.direction.value,
        "trend_confidence": timeframe_analysis.trend.confidence,
        "market_type": timeframe_analysis.sideways_market.market_type.value,
        "breakout_direction": timeframe_analysis.sideways_market.breakout_direction.value,
        "nearest_support_price": nearest_support.price if nearest_support else None,
        "nearest_resistance_price": nearest_resistance.price if nearest_resistance else None,
        "relative_volume": volume.relative_volume if volume else None,
        "relative_volume_level": volume.relative_volume_level.value if volume else None,
    }


def _write_json_report(
    settings: WatchlistServerSettings,
    generated_at: datetime,
    reports: Sequence[dict[str, Any]],
    errors: Sequence[dict[str, str]],
) -> Path:
    path = settings.output_dir / f"watchlist-{_timestamp_slug(generated_at)}.json"
    payload = {
        "generated_at": generated_at.isoformat(),
        "symbols": list(settings.symbols),
        "reports": list(reports),
        "errors": list(errors),
    }
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    return path


def _append_csv_summary(
    settings: WatchlistServerSettings,
    generated_at: datetime,
    reports: Sequence[dict[str, Any]],
    errors: Sequence[dict[str, str]],
) -> Path:
    path = settings.output_dir / "watchlist-summary.csv"
    exists = path.exists()
    with path.open("a", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "generated_at",
                "symbol",
                "status",
                "directional_bias",
                "alignment",
                "confidence",
                "error",
            ],
        )
        if not exists:
            writer.writeheader()
        for report in reports:
            writer.writerow(
                {
                    "generated_at": generated_at.isoformat(),
                    "symbol": report["symbol"],
                    "status": "ok",
                    "directional_bias": report["directional_bias"],
                    "alignment": report["alignment"],
                    "confidence": report["confidence"],
                    "error": "",
                }
            )
        for error in errors:
            writer.writerow(
                {
                    "generated_at": generated_at.isoformat(),
                    "symbol": error["symbol"],
                    "status": "error",
                    "directional_bias": "",
                    "alignment": "",
                    "confidence": "",
                    "error": error["error"],
                }
            )
    return path


def _write_pdf_report(
    settings: WatchlistServerSettings,
    generated_at: datetime,
    reports: Sequence[dict[str, Any]],
    errors: Sequence[dict[str, str]],
) -> Path:
    path = settings.output_dir / f"watchlist-{_timestamp_slug(generated_at)}.pdf"
    lines = [
        f"Generated: {generated_at.isoformat()}",
        f"Symbols: {', '.join(settings.symbols)}",
        "",
    ]
    for report in reports:
        lines.extend(_pdf_report_lines(report))
    if errors:
        lines.append("Errors")
        for error in errors:
            lines.append(f"{error['symbol']}: {error['error']}")
    write_text_pdf(path, title="AtlasTrader Watchlist Market Read", lines=lines)
    return path


def _pdf_report_lines(report: dict[str, Any]) -> list[str]:
    lines = [
        (
            f"{report['symbol']} | bias={report['directional_bias']} "
            f"alignment={report['alignment']} confidence={report['confidence']}"
        ),
        f"conflicts: {', '.join(report['conflicts']) if report['conflicts'] else 'none'}",
    ]
    for timeframe, timeframe_report in report["timeframes"].items():
        lines.append(
            f"  {timeframe} {timeframe_report['role']} | "
            f"close={timeframe_report['latest_close']} "
            f"trend={timeframe_report['trend_direction']} "
            f"bias={timeframe_report['bias']} "
            f"market={timeframe_report['market_type']}"
        )
        lines.append(
            f"    support={timeframe_report['nearest_support_price']} "
            f"resistance={timeframe_report['nearest_resistance_price']} "
            f"rel_vol={timeframe_report['relative_volume']}"
        )
    lines.append("")
    return lines


def _timestamp_slug(value: datetime) -> str:
    return value.strftime("%Y%m%d-%H%M%S")
